[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["David Cuthbert <dacut@kanga.org>"]
edition = "2024"
homepage = "https://github.com/dacut/kanga-dpdk-rs"
license = "Apache-2.0"
repository = "https://github.com/dacut/kanga-dpdk-rs.git"
version = "0.1.0"
